name: Build & Push to GHCR

run-name: Build & Upload Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build Go App
        run: |
          go mod tidy
          go build -o server .

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        id: vars
        run: echo "image=ghcr.io/${{ github.repository_owner }}/koda-b4-backend" >> $GITHUB_OUTPUT

      - name: Extract version
        id: version
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.vars.outputs.image }}:latest \
            -t ${{ steps.vars.outputs.image }}:${{ steps.version.outputs.tag }} .

      - name: Push Docker images
        run: |
          docker push ${{ steps.vars.outputs.image }}:latest
          docker push ${{ steps.vars.outputs.image }}:${{ steps.version.outputs.tag }}
